version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: simplecov
    versions:
    - ">= 0.18.a, < 0.19"
  - dependency-name: capybara
    versions:
    - 3.35.3
  - dependency-name: factory_bot_rails
    versions:
    - 6.1.0
  - dependency-name: capistrano-sidekiq
    versions:
    - 2.0.0
  - dependency-name: sidekiq
    versions:
    - 6.1.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
