inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: '2.4.2'

# copying from Bixby, but adding spec files to that list
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*.gemspec'
    - 'config/**/*'
    - '**/*/catalog_controller.rb'
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Rails/OutputSafety:
  Enabled: false

# our feature tests are super long because they're expensive to run
RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/features/**/*'
