inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: '2.4.3'

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent
  IndentationWidth: 0

Rails/OutputSafety:
  Enabled: false

# our feature tests are super long because they're expensive to run
RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
