version: '3.7'
volumes:
  db:
  fedora:
  rails_public:
  rails_tmp:
  solr:
  spot_derivatives:
  redis:

services:
  app: &app
    build:
      context: .
      target: spot
    image: spot
    volumes:
      - .:/spot
      - rails_public:/spot/public
      - rails_tmp:/spot/tmp
      - spot_derivatives:/spot/tmp/derivatives
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    depends_on:
      - cantaloupe
      - db
      - fedora
      - fitsservlet
      - redis
      - solr
      - db_migrate
    stdin_open: true
    tty: true

  cantaloupe:
    image: uclalibrary/cantaloupe:4.1.5
    volumes:
      - ./config/cantaloupe/delegates.rb:/delegates.rb
      - spot_derivatives:/imageroot
    ports:
      - "8182:8182"
    environment:
      CANTALOUPE_DELEGATE_SCRIPT_ENABLED: 'true'
      CANTALOUPE_DELEGATE_SCRIPT_PATHNAME: /delegates.rb
      CANTALOUPE_FILESYSTEMSOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      CANTALOUPE_BASE_URI: 'http://localhost:8182'
    restart: always

  db:
    image: postgres:alpine
    volumes:
      - db:/data
    environment:
      PGDATA: /data
      POSTGRES_DB: spot_dev
      POSTGRES_USER: spot_dev_user
    restart: always

  db_migrate:
    build:
      context: .
      target: spot-base
    image: spot-base
    env_file: .env
    entrypoint: ["sh", "-c"]
    command: bin/migrate-and-seed-db.sh
    depends_on:
      - db
      - fedora
      - solr
    volumes:
      - .:/spot
      - rails_public:/spot/public
      - rails_tmp:/spot/tmp
      - spot_derivatives:/spot/tmp/derivatives

  fedora:
    image: samvera/fcrepo4:4.7.5
    volumes:
      - fedora:/data
    ports:
      - "8080:8080"
    restart: always

  fitsservlet:
    image: harvardlts/fitsservlet_container:1.4.1
    environment:
      FITSSERVLET_VERSION: '1.1.3'

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

  solr:
    image: solr:7.5-alpine
    volumes:
      - ./solr/config:/spot-config
      - solr:/opt/solr/server/solr
    ports:
      - '8983:8983'
    command: solr-create -c spot-development -d /spot-config
    restart: always

  sidekiq:
    <<: *app
    build:
      context: .
      target: spot-sidekiq
    image: spot-sidekiq
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - ./ingest:/ingest
      - rails_public:/spot/public
      - rails_tmp:/spot/tmp
      - spot_derivatives:/spot/tmp/derviatives
    ports:
      - "3003:3000"
    restart: always
    depends_on:
      - db_migrate
      - app
