version: '3.7'
volumes:
  db:
  fedora:
  solr:
  redis:
services:
  spot: &spot
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      CAS_BASE_URL: ''
      DATABASE_URL: postgres://spot_dev_user:@db/spot_dev
      FEDORA_URL: http://fedora:8984/fedora/rest
      FITS_SERVLET_URL: http://fitsservlet:8080/fits/examine
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      SOLR_URL: http://solr:8983/solr/spot-development
    depends_on:
      - db
      - fedora
      - fitsservlet
      - redis
      - solr
  db:
    image: postgres:alpine
    volumes:
      - db:/data
    environment:
      PGDATA: /data
      POSTGRES_DATABASE: spot_dev
      POSTGRES_USER: spot_dev_user
    ports:
      - 5432:5432
    restart: always
  fedora:
    image: nulib/fcrepo4
    volumes:
      - fedora:/data
    ports:
      - 8984:8080
    restart: always
  fitsservlet:
    image: harvardlts/fitsservlet_container
    ports:
      - 8080:8080
    environment:
      FITSSERVLET_VERSION: '1.1.3'
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - 6380:6379
    restart: always
  solr:
    image: solr:7.5-alpine
    volumes:
      - ./solr/config:/spot-config
      - solr:/opt/solr/server/solr/mycores
    ports:
      - 8983:8983
      - 9985:9983
    command: solr-create -c spot-development -d /spot-config
    restart: always
  sidekiq:
    <<: *spot
    command: bundle exec sidekiq
    volumes:
      - ./ingest:/ingest
    ports:
      - 4000:3000
    depends_on:
      - spot
