version: '3.7'

services:
  app:
    image: lafayettecollegelibraries/spot
    build:
      target: spot-app
      context: .
    volumes:
      - .:/spot
      - rails_public:/spot/public
      - rails_tmp:/spot/tmp
      - gem_storage:/spot/vendor
    ports:
      - "3000:3000"
    environment: &dev_environment
      CAS_BASE_URL: ''
      DEV_USER: dss@lafayette.edu
      FEDORA_URL: http://fedora:8080/rest
      FEDORA_TEST_URL: http://fedora:8080/rest
      FITS_SERVLET_URL: http://fitsservlet:8080/fits
      IIIF_BASE_URL: http://localhost:8182/iiif/2
      PSQL_PASSWORD: spot_dev_pw
      PSQL_HOST: db
      PSQL_USER: spot_dev_user
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
      REDIS_URL: redis://redis:6379
      SOLR_URL: http://solr:8983/solr/spot-development
      SOLR_TEST_URL: http://solr:8983/solr/spot-test
      URL_HOST: http://localhost:3000
    restart: always
    entrypoint: ["bin/spot-dev-entrypoint.sh"]
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    depends_on:
      - cantaloupe
      - db
      - fedora
      - fitsservlet
      - redis
      - solr
      - db_migrate
    stdin_open: true
    tty: true

  cantaloupe:
    image: uclalibrary/cantaloupe:4.1.5
    volumes:
      - ./config/cantaloupe/delegates.rb:/delegates.rb
      - rails_tmp:/imageroot
    ports:
      - "8182:8182"
    environment:
      CANTALOUPE_DELEGATE_SCRIPT_ENABLED: "true"
      CANTALOUPE_DELEGATE_SCRIPT_PATHNAME: /delegates.rb
      CANTALOUPE_FILESYSTEMSOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      CANTALOUPE_BASE_URI: 'http://localhost:8182'
    restart: always

  db:
    image: postgres:9-alpine
    volumes:
      - db:/data
      - ./bin/create-test-db.sql:/docker-entrypoint-initdb.d/10-create-test-db.sql
    environment:
      PGDATA: /data
      POSTGRES_DB: spot_dev
      POSTGRES_USER: spot_dev_user
      POSTGRES_PASSWORD: spot_dev_pw
    restart: always

  db_migrate:
    image: lafayettecollegelibraries/spot
    build: .
    environment:
      <<: *dev_environment
    entrypoint: ["sh", "-c"]
    command: bin/migrate-and-seed-db.sh
    depends_on:
      - db
      - fedora
      - solr
    volumes:
      - .:/spot
      - rails_public:/spot/public
      - rails_tmp:/spot/tmp

  fedora:
    image: samvera/fcrepo4:4.7.5
    volumes:
      - fedora:/data
    restart: always

  fitsservlet:
    image: harvardlts/fitsservlet_container:1.4.1

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

  solr:
    image: solr:7.5-alpine
    volumes:
      - ./solr/config:/spot-config
      - solr:/opt/solr/server/solr
    ports:
      - '8983:8983'
    entrypoint:
      - bash
      - "-c"
      - "precreate-core spot-test /spot-config; precreate-core spot-development /spot-config; exec solr -f"
    restart: always

  sidekiq:
    image: lafayettecollegelibraries/spot
    build:
      context: .
      target: spot-worker
    command:
      - bundle
      - exec
      - sidekiq
    volumes:
      - .:/app
      - ./ingest:/ingest
      - rails_public:/spot/public
      - rails_tmp:/spot/tmp
    environment:
      <<: *dev_environment
    restart: always
    depends_on:
      - db_migrate
      - app

volumes:
  db:
  fedora:
  gem_storage:
  rails_public:
  rails_tmp:
  solr:
  redis:
