version: '3.7'
volumes:
  db:
  fedora:
  solr:
  redis:
services:
  app: &app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      CAS_BASE_URL: ''
      DATABASE_URL: postgres://spot_dev_user:@db:5432/spot_dev
      FEDORA_URL: http://fedora:8080/rest
      FITS_SERVLET_URL: http://fitsservlet:8080/fits
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      SOLR_URL: http://solr:8983/solr/spot-development
      DEV_USER: dss@lafayette.edu
    restart: always
    depends_on:
      - db
      - fedora
      - fitsservlet
      - redis
      - solr
    stdin_open: true
    tty: true

  db:
    image: postgres:alpine
    volumes:
      - db:/data
    environment:
      PGDATA: /data
      POSTGRES_DB: spot_dev
      POSTGRES_USER: spot_dev_user
    restart: always

  fedora:
    image: samvera/fcrepo4:4.7.5
    volumes:
      - fedora:/data
    restart: always

  fitsservlet:
    image: harvardlts/fitsservlet_container:1.4.1
    environment:
      FITSSERVLET_VERSION: '1.1.3'

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

  solr:
    image: solr:7.5-alpine
    volumes:
      - ./solr/config:/spot-config
      - solr:/opt/solr/server/solr
    ports:
      - '8983:8983'
    command: solr-create -c spot-development -d /spot-config
    restart: always

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - ./ingest:/ingest
    ports:
      - "3003:3000"
    restart: always
    depends_on:
      - app
