version: '3.7'

services:
  app:
    image: lafayette/rails_web
    build:
      context: .
      target: spot-development
    volumes:
      - .:/spot
      - ./ingest:/spot/ingest
      - rails_tmp:/spot/tmp
    ports:
      - "443:443"
    env_file:
      - .env.local
    environment:
      AWS_ACCESS_KEY_ID: localstack_access_key
      AWS_SECRET_ACCESS_KEY: localstack_secret_access_key
    depends_on:
      - cantaloupe
      - db
      - fedora
      - redis
      - solr
      - db_migrate
    stdin_open: true
    tty: true
    entrypoint: ["/spot/bin/spot-dev-entrypoint.sh"]
    command: ["bundle", "exec", "rails", "server", "-b", "ssl://0.0.0.0:443?key=/spot/tmp/ssl/application.key&cert=/spot/tmp/ssl/application.crt"]

  cantaloupe:
    image: uclalibrary/cantaloupe:4.1.5
    volumes:
      - ./config/cantaloupe/delegates.rb:/delegates.rb
      - rails_tmp:/spot
    ports:
      - "8182:8182"
    environment:
      CANTALOUPE_DELEGATE_SCRIPT_ENABLED: "true"
      CANTALOUPE_DELEGATE_SCRIPT_PATHNAME: /delegates.rb
      CANTALOUPE_FILESYSTEMSOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      CANTALOUPE_BASE_URI: 'http://localhost:8182'
      DERIVATIVES_PATH: "/spot/derivatives"
    restart: always

  db:
    image: postgres:9.6-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - ./bin/create-dev-dbs.sql:/docker-entrypoint-initdb.d/10-create-dev-dbs.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spot_dev
      POSTGRES_USER: spot_dev_user
      POSTGRES_PASSWORD: spot_dev_pw
    restart: always

  db_migrate:
    image: lafayette/rails_web
    env_file:
      - .env.local
    entrypoint: ["sh", "-c"]
    command: bin/migrate-and-seed-db.sh
    depends_on:
      - db
      - fedora
      - solr

  fedora:
    build:
      context: ./docker/fcrepo
    volumes:
      - fedora:/data:cached
    ports:
      - 8080:8080
    environment:
      FCREPO_POSTGRES_HOST: db
      FCREPO_POSTGRES_USER: spot_fcrepo_dev_user
      FCREPO_POSTGRES_PASSWORD: spot_fcrepo_dev_pw
    restart: always
    depends_on:
      - db

  localstack:
    image: localstack/localstack:latest
    environment:
      AWS_ACCESS_KEY_ID: localstack_access_key
      AWS_SECRET_ACCESS_KEY: localstack_secret_access_key
      AWS_DEFAULT_REGION: us-east-1
      EDGE_PORT: 4566
      SERVICES: s3
      S3_DIR: /tmp/s3-buckets
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '4566-4583:4566-4583'

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always
    ports:
      - 6379:6379

  sidekiq:
    image: lafayette/rails_worker:dev
    build:
      context: .
      target: spot-worker
    env_file:
      - .env.local
    ports:
      - "3003:3000"
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - .:/spot
      - ./ingest:/spot/ingest
      - rails_tmp:/spot/tmp
    restart: always
    depends_on:
      - db
      - fedora
      - redis
      - solr

  solr:
    build:
      context: ./docker/solr
    volumes:
      - solr:/var/solr/data
    ports:
      - "8983:8983"
    environment:
      - SOLR_CORES=spot-development,spot-test
      - SOLR_HOST=solr
    restart: always


volumes:
  db:
  fedora:
  localstack:
  solr:
  rails_tmp:
  redis:
