version: '3.7'

services:
  app:
    image: lafayettecollegelibraries/spot
    build:
      context: .
      target: spot-web-development
    volumes:
      - .:/spot
      - ./ingest:/spot/ingest
      - rails_tmp:/spot/tmp
    ports:
      - "443:443"
    env_file:
      - .env.local
    restart: always
    entrypoint: ["bin/spot-dev-entrypoint.sh"]
    command:
      - "bundle"
      - "exec"
      - "rails"
      - "server"
      - "-b"
      - "ssl://0.0.0.0:443?key=/spot/tmp/ssl/application.key&cert=/spot/tmp/ssl/application.crt"
    depends_on:
      - cantaloupe
      - db
      - fedora
      - fitsservlet
      - redis
      - solr
      - db_migrate
    stdin_open: true
    tty: true

  cantaloupe:
    image: uclalibrary/cantaloupe:4.1.5
    volumes:
      - ./config/cantaloupe/delegates.rb:/delegates.rb
      - rails_tmp:/spot
    ports:
      - "8182:8182"
    environment:
      CANTALOUPE_DELEGATE_SCRIPT_ENABLED: "true"
      CANTALOUPE_DELEGATE_SCRIPT_PATHNAME: /delegates.rb
      CANTALOUPE_FILESYSTEMSOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      CANTALOUPE_BASE_URI: 'http://localhost:8182'
      DERIVATIVES_PATH: "/spot/derivatives"
    restart: always

  db:
    image: postgres:9.6-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - ./bin/create-dev-dbs.sql:/docker-entrypoint-initdb.d/10-create-dev-dbs.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spot_dev
      POSTGRES_USER: spot_dev_user
      POSTGRES_PASSWORD: spot_dev_pw
    restart: always

  db_migrate:
    image: lafayettecollegelibraries/spot
    build:
      context: .
      target: spot-web
    env_file:
      - .env.local
    entrypoint: ["sh", "-c"]
    command: bin/migrate-and-seed-db.sh
    depends_on:
      - db
      - fedora
      - solr

  fedora:
    build:
      context: ./docker/fcrepo
    volumes:
      - fedora:/data:cached
    ports:
      - 8080:8080
    environment:
      FCREPO_POSTGRES_HOST: db
      FCREPO_POSTGRES_USER: spot_fcrepo_dev_user
      FCREPO_POSTGRES_PASSWORD: spot_fcrepo_dev_pw
    restart: always
    depends_on:
      - db

  fitsservlet:
    image: harvardlts/fitsservlet_container:1.4.1

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

  solr:
    image: solr:7.5-alpine
    volumes:
      - ./solr/config:/spot-config
      - solr:/opt/solr/server/solr
    ports:
      - "8983:8983"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core spot-test /spot-config; precreate-core spot-development /spot-config; exec solr -f"
    restart: always

  sidekiq:
    image: lafayettecollegelibraries/spot
    build:
      context: .
      target: spot-worker
    env_file:
      - .env.local
    ports:
      - "3003:3000"
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - .:/spot
      - ./ingest:/spot/ingest
      - rails_tmp:/spot/tmp
    restart: always
    depends_on:
      - db
      - fedora
      - fitsservlet
      - redis
      - solr

volumes:
  derivatives:
  db:
  fedora:
  gem_storage:
  solr:
  rails_tmp:
  redis:
  uploads:
