version: 2.1

jobs:
  echo_skip:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          command: echo "skipping circleci tests"

workflows:
  version: 2
  noop:
    jobs:
      - echo_skip
