# Included in Hyrax::Work
attributes:
  title:
    predicate: http://purl.org/dc/terms/title
    type: string
    multiple: true
    index_keys:
      - "title_sim"
      - "title_tesim"
    form:
      required: true
      primary: true
      multiple: true
  date_modified:
    predicate: http://purl.org/dc/terms/modified
    type: date_time
  date_uploaded:
    precicate: http://purl.org/dc/terms/dateSubmitted
    type: date_time
  depositor:
    predicate: http://id.loc.gov/vocabulary/relators/dpt
    type: string