attributes:
  abstract:
    predicate: http://purl.org/dc/terms/abstract
    type: string
    multiple: true
    form:
      multiple: true
    index_keys:
      - abstract_tesim
  access_note:
    predicate: http://purl.org/dc/terms/accessRights
    type: string
    multiple: true
    form:
      multiple: true
    index_keys:
      - access_note_tesim
  advisor:
    predicate: http://id.loc.gov/vocabulary/relators/ths
    type: string
    multiple: true
    form:
      multiple: true
    index_keys:
      - advisor_ssim
  # dates are edtf values, is there a way we can make this a type?
  date:
    predicate: http://purl.org/dc/terms/date
    type: string
    multiple: true
    form:
      multiple: true
    index_keys:
      - date_ssim
  date_available:
    predicate: http://purl.org/dc/terms/available
    type: string
    multiple: true
    form:
      multiple: true
    index_keys:
      - date_available_ssim
