terms:
  # academic departments
  - Africana Studies
  - Anthropology & Sociology
  - Art
  - Biology
  - Chemical & Biomolecular Engineering
  - Chemistry
  - Civil & Environmental Engineering
  - Computer Science
  - Economics
  - Electrical & Computer Engineering
  - Engineering Studies
  - English
  - Foreign Languages & Literatures
  - Geology & Environmental Geosciences
  - Government & Law
  - History
  - Libraries
  - Mathematics
  - Mechanical Engineering
  - Music
  - Philosophy
  - Physics
  - Policy Studies
  - Psychology
  - Religious Studies
  - Theater
  
  # administrative content
  - Communication
  - Development
  - Facility Planning and Construction
  - Finance and Administration
  - Office of Institutional Research
  - Office of Student Development
  - Office of the Registrar
  - Parent Relations
  - President's Office
  - Provost's Office
  - Public Safety