terms:
  - Athletics
  - Board of Trustees
  - College Archives
  - Communications
  - Development
  - Engineering
  - Facility Planning and Construction
  - Finance and Administration
  - Humanities
  - Natural Sciences
  - Office of Institutional Research
  - Office of Student Development
  - Office of the Registrar
  - Parent Relations
  - President’s Office
  - Provost’s Office
  - Public Safety
  - Social Sciences
  - Student Publications
