terms:
  - Administrative Content
  - Africana Studies
  - Anthropology & Sociology
  - Art
  - Asian Studies
  - Biology
  - Center for the Integration of Teaching, Learning, and Scholarship
  - Chemical & Biomolecular Engineering
  - Chemistry
  - Civil & Environmental Engineering
  - Computer Science
  - Economics
  - Electrical & Computer Engineering
  - Engineering Studies
  - English
  - Environmental Science & Studies
  - Film & Media Studies
  - Geology & Environmental Geosciences
  - Government & Law
  - History
  - International Affairs
  - Languages and Literary Studies
  - Libraries
  - Mathematics
  - Mechanical Engineering
  - Music
  - Neuroscience
  - Philosophy
  - Physics
  - Policy Studies
  - Psychology
  - Religious Studies
  - Russian and East European Studies
  - Theater
  - Women's, Gender & Sexuality Studies
