terms:
  - id: fast
    label: FAST
    search: /authorities/search/assign_fast/all
  - id: geonames
    label: GeoNames
    search: /authorities/search/geonames
  - id: tgn
    label: Getty Thesaurus of Geo. Names
    search: /authorities/search/getty/tgn
