terms:
  - Article
  - Audio
  - Book
  - Conference Proceedings
  - Dataset
  - Image
  - Map or Cartographic Material
  - Part of Book
  - Periodicial
  - Postcard
  - Poster
  - Presentation
  - Project
  - Report
  - Research Paper
  - Software or Program Code
  - Transcript
  - Video
  - Other
