terms:
  # the Europeana 14
  -
    term: Public Domain Mark (PDM)
    id: http://creativecommons.org/publicdomain/mark/1.0/
  -
    term: No Copyright - non commercial re-use only (NoC-NC)
    id: http://rightsstatements.org/vocab/NoC-NC/1.0/
  -
    term: No Copyright - Other Known Legal Restriction (NoC-OKLR)
    id: http://rightsstatements.org/vocab/NoC-OKLR/1.0/
  -
    term: Creative Commons CC0 1.0 Universal Public Domain Dedication (CC0)
    id: http://creativecommons.org/publicdomain/zero/1.0/
  -
    term: Creative Commons - Attribution (BY)
    id: http://creativecommons.org/licenses/by/4.0/
  -
    term: Creative Commons - Attribution, ShareAlike (BY-SA)
    id: http://creativecommons.org/licenses/by-sa/4.0/
  -
    term: Creative Commons - Attribution, No Derivatives (BY-ND)
    id: http://creativecommons.org/licenses/by-nd/4.0/
  -
    term: Creative Commons - Attribution, Non-Commercial (BY-NC)
    id: http://creativecommons.org/licenses/by-nc/4.0/
  -
    term: Creative Commons - Attribution, Non-Commercial, ShareAlike (BY-NC-SA)
    id: http://creativecommons.org/licenses/by-nc-sa/4.0/
  -
    term: Creative Commons - Attribution, Non-Commercial, No Derivatives (BY-NC-ND)
    id:  http://creativecommons.org/licenses/by-nc-nd/4.0/
  -
    term: In Copyright (InC)
    id: http://rightsstatements.org/vocab/InC/1.0/
  -
    term: In Copyright - Educational Use Permitted (InC-EDU)
    id: http://rightsstatements.org/vocab/InC-EDU/1.0/
  -
    term: In Copyright - EU Orphan Work (InC-EU-OW)
    id: http://rightsstatements.org/vocab/InC-OW-EU/1.0/
  -
    term: Copyright Not Evaluated (CNE)
    id: http://rightsstatements.org/vocab/CNE/1.0/

  # our additional 6
  -
    term: In Copyright - Non-Commercial Use Permitted (InC-NC)
    id: http://rightsstatements.org/vocab/InC-NC/1.0/
  -
    term: In Copyright - Rights-holder(s) Unlocatable or Unidentifiable (InC-RUU)
    id: http://rightsstatements.org/vocab/InC-RUU/1.0/
  -
    term: No Copyright - Contractual Restrictions (NoC-CR)
    id: http://rightsstatements.org/vocab/NoC-CR/1.0/
  -
    term: No Copyright - United States (NoC-US)
    id: http://rightsstatements.org/vocab/NoC-US/1.0/
  -
    term: Copyright Undetermined (UND)
    id: http://rightsstatements.org/vocab/UND/1.0/
  -
    term: No Known Copyright (NKC)
    id: http://rightsstatements.org/vocab/NKC/1.0/
