terms:
  - 000 MATERIAL NOT RELEVANT
  - 100 ORIENTATION
  - 101 IDENTIFICATION
  - 102 MAPS
  - 103 PLACE NAMES
  - 104 GLOSSARY
  - 105 CULTURE SUMMARY
  - 106 CODED DATA
  - 107 DIAGNOSTIC MATERIAL ATTRIBUTES
  - 110 INFORMATION SOURCES
  - 111 CITATIONS OF DOCUMENTS IN THE HRAF COLLECTION
  - 112 ADDITIONAL BIBLIOGRAPHY
  - 113 BIBLIOGRAPHIES IN SOURCES
  - 114 REVIEWS AND CRITIQUES
  - 115 INFORMANTS
  - 116 COMPLETE TEXTS OF HRAF DOCUMENTS
  - 117 FIELD DATA
  - 118 FICTION
  - 119 ARTIFACT AND ARCHIVE COLLECTIONS
  - 120 RESEARCH METHODS
  - 121 THEORETICAL ORIENTATION
  - 1210 ARCHAEOLOGICAL EXCAVATION METHODS
  - 1211 DATING METHODS IN ARCHAEOLOGY
  - 1212 LABORATORY ANALYSIS IN ARCHAEOLOGY
  - 1213 EXPERIMENTAL DATA
  - 122 PRACTICAL PREPARATIONS OF FIELDWORK
  - 123 OBSERVATION IN RESEARCH
  - 124 INTERVIEWING IN RESEARCH
  - 125 TESTS AND SCHEDULES IN THE FIELD
  - 126 RECORDING AND COLLECTING IN THE FIELD
  - 127 HISTORICAL AND ARCHIVAL RESEARCH
  - 128 ORGANIZATION AND ANALYSIS OF RESULTS
  - 129 ARCHAEOLOGICAL SURVEY METHODS
  - 130 GEOGRAPHY
  - 131 LOCATION
  - 132 CLIMATE
  - 133 TOPOGRAPHY AND GEOLOGY
  - 134 SOIL
  - 135 MINERAL RESOURCES
  - 136 FAUNA
  - 137 FLORA
  - 138 POST DEPOSITIONAL PROCESSES
  - 140 HUMAN BIOLOGY
  - 141 ANTHROPOMETRY
  - 142 DESCRIPTIVE SOMATOLOGY
  - 143 GENETICS
  - 144 RACIAL IDENTIFICATION
  - 145 ONTOGENETIC DATA
  - 146 NUTRITION
  - 147 PHYSIOLOGICAL DATA
  - 150 BEHAVIOR PROCESSES AND PERSONALITY
  - 151 SENSATION AND PERCEPTION
  - 152 DRIVES AND EMOTIONS
  - 153 MODIFICATION OF BEHAVIOR
  - 154 ADJUSTMENT PROCESSES
  - 155 PERSONALITY DEVELOPMENT
  - 156 SOCIAL PERSONALITY
  - 157 PERSONALITY TRAITS
  - 158 PERSONALITY DISORDERS
  - 159 LIFE HISTORY MATERIALS
  - 160 DEMOGRAPHY
  - 161 POPULATION
  - 162 COMPOSITION OF POPULATION
  - 163 BIRTH STATISTICS
  - 164 MORBIDITY
  - 165 MORTALITY
  - 166 INTERNAL MIGRATION
  - 167 EXTERNAL MIGRATION
  - 168 POPULATION POLICY
  - 170 HISTORY AND CULTURE CHANGE
  - 171 COMPARATIVE EVIDENCE
  - 1710 CULTURAL REVITALIZATION AND ETHNOGENESIS
  - 172 PREHISTORY
  - 173 TRADITIONAL HISTORY
  - 174 HISTORICAL RECONSTRUCTION
  - 175 HISTORY
  - 176 INNOVATION
  - 177 ACCULTURATION AND CULTURE CONTACT
  - 178 SOCIOCULTURAL TRENDS
  - 179 ECONOMIC PLANNING AND DEVELOPMENT
  - 180 TOTAL CULTURE
  - 181 ETHOS
  - 182 FUNCTIONAL/ADAPTATIONAL INTERPRETATIONS
  - 183 NORMS
  - 184 CULTURAL PARTICIPATION
  - 185 CULTURAL GOALS
  - 186 CULTURAL IDENTITY AND PRIDE
  - 190 LANGUAGE
  - 191 SPEECH
  - 192 VOCABULARY
  - 193 GRAMMAR
  - 194 PHONOLOGY
  - 195 SOCIOLINGUISTICS
  - 196 SEMANTICS
  - 197 LINGUISTIC IDENTIFICATION
  - 198 SPECIAL LANGUAGES
  - 200 COMMUNICATION
  - 201 GESTURES AND SIGNS
  - 2010 INTERNET COMMUNICATIONS
  - 202 TRANSMISSION OF MESSAGES
  - 203 DISSEMINATION OF NEWS AND INFORMATION
  - 204 PRESS
  - 205 MAIL
  - 206 TELEPHONE AND TELEGRAPH
  - 207 RADIO AND TELEVISION
  - 208 PUBLIC OPINION
  - 209 PROXEMICS
  - 210 RECORDS
  - 211 MNEMONIC DEVICES
  - 212 WRITING
  - 213 PRINTING
  - 214 PUBLISHING
  - 215 PHOTOGRAPHY
  - 216 AUDIOVISUAL RECORDS AND EQUIPMENT
  - 217 ARCHIVES
  - 218 WRITING AND PRINTING SUPPLIES
  - 220 FOOD QUEST
  - 221 ANNUAL CYCLE
  - 222 COLLECTING
  - 223 FOWLING
  - 224 HUNTING AND TRAPPING
  - 225 MARINE HUNTING
  - 226 FISHING
  - 227 FISHING GEAR
  - 228 MARINE INDUSTRIES
  - 230 ANIMAL HUSBANDRY
  - 231 DOMESTICATED ANIMALS
  - 232 APPLIED ANIMAL SCIENCE
  - 233 PASTORAL ACTIVITIES
  - 234 DAIRYING
  - 235 POULTRY RAISING
  - 236 WOOL PRODUCTION
  - 237 ANIMAL BY-PRODUCTS
  - 240 AGRICULTURE
  - 241 TILLAGE
  - 242 AGRICULTURAL SCIENCE
  - 243 CEREAL AGRICULTURE
  - 244 VEGETABLE PRODUCTION
  - 245 ARBORICULTURE
  - 246 FORAGE CROPS
  - 247 FLORICULTURE
  - 248 TEXTILE AGRICULTURE
  - 249 SPECIAL CROPS
  - 250 FOOD PROCESSING
  - 251 PRESERVATION AND STORAGE OF FOOD
  - 252 FOOD PREPARATION
  - 253 MEAT PACKING INDUSTRY
  - 254 REFRIGERATION INDUSTRY
  - 255 CANNING INDUSTRY
  - 256 CEREAL INDUSTRY
  - 257 CONFECTIONERY INDUSTRIES
  - 258 OTHER FOOD PROCESSING INDUSTRIES
  - 260 FOOD CONSUMPTION
  - 261 GRATIFICATION AND CONTROL OF HUNGER
  - 262 DIET
  - 263 CONDIMENTS
  - 264 EATING
  - 265 FOOD SERVICE INDUSTRIES
  - 266 CANNIBALISM
  - 270 DRINK AND DRUGS
  - 271 WATER AND THIRST
  - 272 NONALCOHOLIC BEVERAGES
  - 273 ALCOHOLIC BEVERAGES
  - 274 BEVERAGE INDUSTRIES
  - 275 DRINKING ESTABLISHMENTS
  - 276 RECREATIONAL AND NON-THERAPEUTIC DRUGS
  - 277 TOBACCO INDUSTRY
  - 278 PHARMACEUTICALS
  - 280 LEATHER, TEXTILES, AND FABRICS
  - 281 WORK IN SKINS
  - 282 LEATHER INDUSTRY
  - 283 CORDAGE
  - 284 KNOTS AND LASHINGS
  - 285 MATS AND BASKETRY
  - 286 WOVEN AND OTHER INTERWORKED FABRICS
  - 287 FELTED AND OTHER NON-INTERWORKED FABRICS
  - 288 TEXTILE INDUSTRIES
  - 289 PAPER INDUSTRY
  - 290 CLOTHING
  - 291 NORMAL GARB
  - 292 SPECIAL GARMENTS
  - 293 PARAPHERNALIA
  - 294 CLOTHING MANUFACTURE
  - 295 SPECIAL CLOTHING INDUSTRIES
  - 296 GARMENT CARE
  - 300 ADORNMENT
  - 301 ORNAMENT
  - 302 PERSONAL GROOMING
  - 303 MAKING OF GROOMING ACCESSORIES
  - 304 BODY ALTERATIONS
  - 305 BEAUTY SPECIALISTS
  - 306 JEWELRY MANUFACTURE
  - 310 EXPLOITATIVE ACTIVITIES
  - 311 LAND USE
  - 312 WATER SUPPLY
  - 313 LUMBERING
  - 314 FOREST PRODUCTS
  - 315 OIL AND GAS WELLS
  - 316 MINING AND QUARRYING
  - 317 SPECIAL DEPOSITS
  - 318 ENVIRONMENTAL QUALITY
  - 320 PROCESSING OF BASIC MATERIALS
  - 321 BONE, HORN, AND SHELL TECHNOLOGY
  - 322 WOODWORKING
  - 323 CERAMIC TECHNOLOGY
  - 324 LITHIC INDUSTRIES
  - 325 METALLURGY
  - 326 SMITHS AND THEIR CRAFTS
  - 327 IRON AND STEEL INDUSTRY
  - 328 NONFERROUS METAL INDUSTRIES
  - 330 BUILDING AND CONSTRUCTION
  - 331 CONSTRUCTION
  - 332 EARTH MOVING
  - 333 MASONRY
  - 334 STRUCTURAL STEEL WORK
  - 335 CARPENTRY
  - 336 PLUMBING
  - 337 ELECTRICAL INSTALLATION
  - 338 MISCELLANEOUS BUILDING TRADES
  - 339 BUILDING SUPPLIES INDUSTRIES
  - 340 STRUCTURES
  - 341 ARCHITECTURE
  - 342 DWELLINGS
  - 343 OUTBUILDINGS
  - 344 PUBLIC STRUCTURES
  - 345 RECREATIONAL STRUCTURES
  - 346 RELIGIOUS AND EDUCATIONAL STRUCTURES
  - 347 BUSINESS STRUCTURES
  - 348 INDUSTRIAL STRUCTURES
  - 349 MISCELLANEOUS STRUCTURES
  - 350 EQUIPMENT AND MAINTENANCE OF BUILDINGS
  - 351 GROUNDS
  - 352 FURNITURE
  - 353 BUILDING INTERIORS AND ARRANGEMENT
  - 354 HEATING AND LIGHTING EQUIPMENT
  - 355 MISCELLANEOUS BUILDING EQUIPMENT
  - 356 HOUSEKEEPING
  - 357 DOMESTIC SERVICE
  - 358 MAINTENANCE OF NON-DOMESTIC BUILDINGS
  - 360 SETTLEMENTS
  - 361 SETTLEMENT PATTERNS
  - 362 HOUSING
  - 363 STREETS AND TRAFFIC
  - 364 REFUSE DISPOSAL AND SANITARY FACILITIES
  - 365 PUBLIC UTILITIES
  - 366 COMMERCIAL FACILITIES
  - 367 PARKS
  - 368 MISCELLANEOUS FACILITIES
  - 369 URBAN AND RURAL LIFE
  - 370 ENERGY AND POWER
  - 371 POWER DEVELOPMENT
  - 372 FIRE
  - 373 LIGHT
  - 374 HEAT
  - 375 THERMAL POWER
  - 376 WATER POWER
  - 377 ELECTRIC POWER
  - 378 ATOMIC ENERGY
  - 379 MISCELLANEOUS POWER PRODUCTION
  - 380 CHEMICAL INDUSTRIES
  - 381 CHEMICAL ENGINEERING
  - 382 PETROLEUM AND COAL PRODUCTS INDUSTRIES
  - 383 RUBBER INDUSTRY
  - 384 SYNTHETICS INDUSTRY
  - 385 INDUSTRIAL CHEMICALS
  - 386 PAINT AND DYE MANUFACTURE
  - 387 FERTILIZER INDUSTRY
  - 388 SOAP AND ALLIED PRODUCTS
  - 389 MANUFACTURE OF EXPLOSIVES
  - 390 CAPITAL GOODS INDUSTRIES
  - 391 HARDWARE MANUFACTURE
  - 392 MACHINE INDUSTRIES
  - 393 ELECTRICAL SUPPLIES INDUSTRY
  - 394 MAKING OF HEATING, LIGHTING EQUIPMENT
  - 395 MAKING OF OPTICAL AND PHOTO EQUIPMENT
  - 396 SHIPBUILDING
  - 397 RAILWAY EQUIPMENT INDUSTRY
  - 398 MANUFACTURE OF VEHICLES
  - 399 AIRCRAFT INDUSTRY
  - 400 MACHINES
  - 401 MECHANICS
  - 402 INDUSTRIAL MACHINERY
  - 403 ELECTRICAL MACHINES AND APPLIANCES
  - 404 HOUSEHOLD MACHINES AND APPLIANCES
  - 405 MEASURING AND RECORDING DEVICES
  - 406 WEIGHT-MOVING MACHINERY
  - 407 AGRICULTURAL MACHINERY
  - 408 COMPUTER TECHNOLOGY
  - 410 TOOLS AND APPLIANCES
  - 411 WEAPONS
  - 412 GENERAL TOOLS
  - 413 SPECIAL TOOLS
  - 414 MISCELLANEOUS HARDWARE
  - 415 UTENSILS
  - 416 APPLIANCES
  - 417 APPARATUS
  - 420 PROPERTY
  - 421 PROPERTY SYSTEM
  - 422 PROPERTY IN MOVABLES
  - 423 REAL PROPERTY
  - 424 INCORPOREAL PROPERTY
  - 425 CHANGES IN PROPERTY RIGHTS
  - 426 BORROWING AND LENDING
  - 427 RENTING AND LEASING
  - 428 INHERITANCE
  - 429 ADMINISTRATION
  - 430 EXCHANGE AND TRANSFERS
  - 431 GIFT GIVING
  - 432 BUYING AND SELLING
  - 433 PRODUCTION AND SUPPLY
  - 434 INCOME AND DEMAND
  - 435 PRICE AND VALUE
  - 436 MEDIUM OF EXCHANGE
  - 437 EXCHANGE TRANSACTIONS
  - 438 INTERNAL TRADE
  - 439 EXTERNAL TRADE
  - 440 MARKETING
  - 441 MERCANTILE BUSINESS
  - 442 WHOLESALE MARKETING
  - 443 RETAIL MARKETING
  - 444 RETAIL BUSINESSES
  - 445 SERVICE INDUSTRIES
  - 446 SALES PROMOTION
  - 447 ADVERTISING
  - 450 FINANCE
  - 451 ACCOUNTING
  - 452 CREDIT
  - 453 BANKING
  - 454 SAVING AND INVESTMENT
  - 455 SPECULATION
  - 456 INSURANCE
  - 457 FOREIGN EXCHANGE
  - 458 BUSINESS CYCLES
  - 460 LABOR
  - 461 LABOR AND LEISURE
  - 462 DIVISION OF LABOR BY GENDER
  - 463 OCCUPATIONAL SPECIALIZATION
  - 464 LABOR SUPPLY AND EMPLOYMENT
  - 465 WAGES AND SALARIES
  - 466 LABOR RELATIONS
  - 467 LABOR ORGANIZATION
  - 468 COLLECTIVE BARGAINING
  - 470 BUSINESS AND INDUSTRIAL ORGANIZATION
  - 471 OWNERSHIP AND CONTROL OF CAPITAL
  - 472 INDIVIDUAL ENTERPRISE
  - 473 CORPORATE ORGANIZATION
  - 474 COOPERATIVE ORGANIZATION
  - 475 STATE ENTERPRISE
  - 476 MUTUAL AID
  - 477 COMPETITION
  - 480 TRAVEL AND TRANSPORTATION
  - 481 LOCOMOTION
  - 482 BURDEN CARRYING
  - 483 WEIGHT MOVING
  - 484 TRAVEL
  - 485 TRAVEL SERVICES
  - 486 REGULATION OF TRAVEL
  - 487 ROUTES
  - 488 WAREHOUSING
  - 489 TRANSPORTATION
  - 490 LAND TRANSPORT
  - 491 HIGHWAYS AND BRIDGES
  - 492 ANIMAL TRANSPORT
  - 493 VEHICLES
  - 494 HIGHWAY TRANSPORT
  - 495 AUXILIARY HIGHWAY SERVICES
  - 496 RAILWAYS
  - 497 RAIL TRANSPORT
  - 498 TERMINAL FACILITIES
  - 499 HIGHWAY AND RAILWAY CONSTRUCTION
  - 500 WATER, AIR, AND SPACE TRANSPORT
  - 501 BOATS
  - 502 NAVIGATION
  - 503 WATERWAYS IMPROVEMENTS
  - 504 PORT FACILITIES
  - 505 WATER TRANSPORT
  - 506 AIRCRAFT
  - 507 AVIATION
  - 508 AIRPORT FACILITIES
  - 509 AIR TRANSPORT
  - 510 LIVING STANDARDS AND ROUTINES
  - 511 STANDARD OF LIVING
  - 512 DAILY ROUTINE
  - 513 SLEEPING
  - 514 ELIMINATION
  - 515 PERSONAL HYGIENE
  - 516 POSTURES
  - 517 LEISURE TIME ACTIVITIES
  - 520 RECREATION
  - 521 CONVERSATION
  - 522 HUMOR
  - 523 HOBBIES
  - 524 GAMES
  - 525 GAMBLING
  - 526 ATHLETIC SPORTS
  - 527 REST DAYS AND HOLIDAYS
  - 528 VACATIONS
  - 529 RECREATIONAL FACILITIES
  - 530 ART
  - 531 DECORATIVE ART
  - 5310 VERBAL ARTS
  - 5311 VISUAL ARTS
  - 532 REPRESENTATIVE ART
  - 533 MUSIC
  - 534 MUSICAL INSTRUMENTS
  - 535 DANCE
  - 536 DRAMA
  - 537 ORATORY
  - 538 LITERATURE
  - 539 LITERARY TEXTS
  - 540 COMMERCIALIZED ENTERTAINMENT
  - 541 SPECTACLES
  - 542 COMMERCIALIZED SPORTS
  - 543 EXHIBITIONS
  - 544 PUBLIC LECTURES
  - 545 MUSICAL AND THEATRICAL PRODUCTIONS
  - 546 MOTION PICTURE INDUSTRY
  - 547 NIGHT CLUBS AND CABARETS
  - 548 ILLEGAL ENTERTAINMENT
  - 549 ART AND RECREATIONAL SUPPLIES INDUSTRIES
  - 550 NAMING, PRESTIGE AND STATUS MOBILITY
  - 551 PERSONAL NAMES
  - 552 NAMES OF ANIMALS AND THINGS
  - 553 NAMING
  - 554 STATUS, ROLE, AND PRESTIGE
  - 555 TALENT MOBILITY
  - 556 ACCUMULATION OF WEALTH
  - 557 MANIPULATIVE MOBILITY
  - 558 DOWNWARD MOBILITY
  - 560 SOCIAL STRATIFICATION
  - 561 AGE STRATIFICATION
  - 562 GENDER STATUS
  - 563 ETHNIC STRATIFICATION
  - 564 CASTES
  - 565 CLASSES
  - 566 SERFDOM AND PEONAGE
  - 567 SLAVERY
  - 570 INTERPERSONAL RELATIONS
  - 571 SOCIAL RELATIONSHIPS AND GROUPS
  - 572 FRIENDSHIPS
  - 573 CLIQUES
  - 574 VISITING AND HOSPITALITY
  - 575 SODALITIES
  - 576 ETIQUETTE
  - 577 ETHICS
  - 578 INGROUP ANTAGONISMS
  - 579 BRAWLS, RIOTS, AND BANDITRY
  - 580 MARRIAGE
  - 581 BASIS OF MARRIAGE
  - 582 REGULATION OF MARRIAGE
  - 583 MODE OF MARRIAGE
  - 584 ARRANGING A MARRIAGE
  - 585 NUPTIALS
  - 586 TERMINATION OF MARRIAGE
  - 587 SECONDARY MARRIAGES
  - 588 SPECIAL UNIONS AND MARRIAGES
  - 589 CELIBACY
  - 590 FAMILY
  - 591 RESIDENCE
  - 592 HOUSEHOLD
  - 593 FAMILY RELATIONSHIPS
  - 594 NUCLEAR FAMILY
  - 595 POLYGAMY
  - 596 EXTENDED FAMILIES
  - 597 ADOPTION
  - 600 KINSHIP
  - 601 KINSHIP TERMINOLOGY
  - 602 KIN RELATIONSHIPS
  - 603 GRANDPARENTS AND GRANDCHILDREN
  - 604 AVUNCULAR AND NEPOTIC RELATIVES
  - 605 COUSINS
  - 606 PARENTS-IN-LAW AND CHILDREN-IN-LAW
  - 607 SIBLINGS-IN-LAW
  - 608 ARTIFICIAL KIN RELATIONSHIPS
  - 609 BEHAVIOR TOWARD NON-RELATIVES
  - 610 KIN GROUPS
  - 611 RULE OF DESCENT
  - 612 KINDREDS AND RAMAGES
  - 613 LINEAGES
  - 614 CLANS
  - 615 PHRATRIES
  - 616 MOIETIES
  - 617 BILINEAL KIN GROUPS
  - 618 LOCALIZED KIN GROUPS
  - 619 TRIBE AND NATION
  - 620 COMMUNITY
  - 621 COMMUNITY STRUCTURE
  - 622 COMMUNITY HEADS
  - 623 COMMUNITY COUNCILS
  - 624 LOCAL OFFICIALS
  - 625 POLICE
  - 626 SOCIAL CONTROL
  - 627 INFORMAL IN-GROUP JUSTICE
  - 628 INTER-COMMUNITY RELATIONS
  - 629 INTER-ETHNIC RELATIONS
  - 630 TERRITORIAL ORGANIZATION
  - 631 TERRITORIAL HIERARCHY
  - 632 TOWNS
  - 633 CITIES
  - 634 DISTRICTS
  - 635 PROVINCES
  - 636 DEPENDENCIES
  - 640 GOVERNMENT INSTITUTIONS
  - 641 CITIZENSHIP
  - 642 FORM AND RULES OF GOVERNMENT
  - 643 CHIEF EXECUTIVE
  - 644 EXECUTIVE HOUSEHOLD
  - 645 ADVISERS TO THE CHIEF EXECUTIVE
  - 646 DELIBERATIVE COUNCILS
  - 647 ADMINISTRATIVE AGENCIES
  - 648 EXTERNAL RELATIONS
  - 650 GOVERNMENT ACTIVITIES
  - 651 TAXATION AND PUBLIC INCOME
  - 652 PUBLIC FINANCE
  - 653 PUBLIC WORKS
  - 654 RESEARCH AND DEVELOPMENT
  - 655 GOVERNMENT ENTERPRISES
  - 656 GOVERNMENT REGULATION
  - 657 PUBLIC WELFARE
  - 658 PUBLIC EDUCATION
  - 659 MISCELLANEOUS GOVERNMENT ACTIVITIES
  - 660 POLITICAL BEHAVIOR
  - 661 EXPLOITATION
  - 662 POLITICAL INTRIGUE
  - 663 PUBLIC SERVICE
  - 664 PRESSURE POLITICS
  - 665 POLITICAL PARTIES
  - 666 ELECTIONS
  - 667 POLITICAL MACHINES
  - 668 POLITICAL MOVEMENTS
  - 669 REVOLUTION
  - 670 LAW
  - 671 LEGAL NORMS
  - 672 LIABILITY
  - 673 WRONGS
  - 674 CRIME
  - 675 CONTRACTS
  - 676 AGENCY
  - 677 ORGANIZED CRIME
  - 680 OFFENSES AND SANCTIONS
  - 681 SANCTIONS
  - 682 OFFENSES AGAINST LIFE
  - 683 OFFENSES AGAINST THE PERSON
  - 684 SEX AND MARITAL OFFENSES
  - 685 PROPERTY OFFENSES
  - 686 NONFULFILLMENT OF OBLIGATIONS
  - 687 OFFENSES AGAINST THE STATE
  - 688 RELIGIOUS OFFENSES
  - 689 SOCIAL OFFENSES
  - 690 JUSTICE
  - 691 LITIGATION
  - 692 JUDICIAL AUTHORITY
  - 693 LEGAL AND JUDICIAL PERSONNEL
  - 694 INITIATION OF JUDICIAL PROCEEDINGS
  - 695 TRIAL PROCEDURE
  - 696 EXECUTION OF JUSTICE
  - 697 PRISONS AND JAILS
  - 698 SPECIAL COURTS
  - 700 ARMED FORCES
  - 701 MILITARY ORGANIZATION
  - 702 RECRUITMENT AND TRAINING
  - 703 DISCIPLINE AND MORALE
  - 704 GROUND COMBAT FORCES
  - 705 SUPPLY AND COMMISSARIAT
  - 706 NAVY
  - 707 AIR FORCES
  - 708 AUXILIARY CORPS
  - 710 MILITARY TECHNOLOGY
  - 711 MILITARY ENGINEERING
  - 712 MILITARY INSTALLATIONS
  - 713 ORDNANCE
  - 714 UNIFORM AND ACCOUTERMENT
  - 715 MILITARY VEHICLES
  - 716 NAVAL VESSELS
  - 717 MILITARY AIRCRAFT
  - 718 SPECIAL MILITARY EQUIPMENT
  - 719 MUNITIONS INDUSTRIES
  - 720 WAR
  - 721 INSTIGATION OF WAR
  - 722 WARTIME ADJUSTMENTS
  - 723 STRATEGY
  - 724 LOGISTICS
  - 725 TACTICS
  - 726 WARFARE
  - 727 AFTERMATH OF COMBAT
  - 728 PEACEMAKING
  - 729 WAR VETERANS
  - 730 SOCIAL PROBLEMS
  - 731 DISASTERS
  - 732 DISABILITIES
  - 733 ALCOHOLISM AND DRUG ADDICTION
  - 734 INVALIDISM
  - 735 POVERTY
  - 736 DEPENDENCY
  - 737 OLD AGE DEPENDENCY
  - 738 DELINQUENCY
  - 740 HEALTH AND WELFARE
  - 741 PHILANTHROPIC FOUNDATIONS
  - 742 MEDICAL RESEARCH
  - 743 HOSPITALS AND CLINICS
  - 744 PUBLIC HEALTH AND SANITATION
  - 745 SOCIAL INSURANCE
  - 746 PUBLIC ASSISTANCE
  - 747 PRIVATE WELFARE AGENCIES
  - 748 SOCIAL WORK
  - 750 SICKNESS
  - 751 PREVENTIVE MEDICINE
  - 752 BODILY INJURIES
  - 753 THEORY OF DISEASE
  - 754 SORCERY
  - 755 MAGICAL AND MENTAL THERAPY
  - 756 SHAMANS AND PSYCHOTHERAPISTS
  - 757 MEDICAL THERAPY
  - 758 MEDICAL CARE
  - 759 MEDICAL PERSONNEL
  - 760 DEATH
  - 761 LIFE AND DEATH
  - 762 SUICIDE
  - 763 DYING
  - 764 BURIAL PRACTICES AND FUNERALS
  - 765 MOURNING
  - 766 SPECIAL BURIAL PRACTICES AND FUNERALS
  - 767 MORTUARY SPECIALISTS
  - 768 SOCIAL READJUSTMENTS TO DEATH
  - 769 CULT OF THE DEAD
  - 770 RELIGIOUS BELIEFS
  - 771 GENERAL CHARACTER OF RELIGION
  - 772 COSMOLOGY
  - 773 MYTHOLOGY
  - 774 ANIMISM
  - 775 ESCHATOLOGY
  - 776 SPIRITS AND GODS
  - 777 LUCK AND CHANCE
  - 778 SACRED OBJECTS AND PLACES
  - 779 THEOLOGICAL SYSTEMS
  - 780 RELIGIOUS PRACTICES
  - 781 RELIGIOUS EXPERIENCE
  - 782 PRAYERS AND SACRIFICES
  - 783 PURIFICATION AND ATONEMENT
  - 784 AVOIDANCE AND TABOO
  - 785 ASCETICISM
  - 786 ECSTATIC RELIGIOUS PRACTICES
  - 787 REVELATION AND DIVINATION
  - 788 RITUAL
  - 789 MAGIC
  - 790 ECCLESIASTICAL ORGANIZATION
  - 791 MAGICIANS AND DIVINERS
  - 792 PROPHETS AND ASCETICS
  - 793 PRIESTHOOD
  - 794 CONGREGATIONS
  - 795 RELIGIOUS DENOMINATIONS
  - 796 ORGANIZED CEREMONIAL
  - 797 MISSIONS
  - 798 RELIGIOUS INTOLERANCE AND MARTYRS
  - 800 NUMBERS AND MEASURES
  - 801 NUMEROLOGY
  - 802 NUMERATION
  - 803 MATHEMATICS
  - 804 WEIGHTS AND MEASURES
  - 805 ORDERING OF TIME
  - 810 SCIENCES AND HUMANITIES
  - 811 LOGIC
  - 812 PHILOSOPHY
  - 813 SCIENTIFIC METHOD
  - 814 HUMANISTIC STUDIES
  - 815 SCIENCE
  - 816 APPLIED SCIENCE
  - 820 IDEAS ABOUT NATURE AND PEOPLE
  - 821 ETHNOMETEOROLOGY
  - 822 ETHNOPHYSICS
  - 823 ETHNOGEOGRAPHY
  - 824 ETHNOBOTANY
  - 825 ETHNOZOOLOGY
  - 826 ETHNOANATOMY
  - 827 ETHNOPHYSIOLOGY
  - 828 ETHNOPSYCHOLOGY
  - 829 ETHNOSOCIOLOGY
  - 830 SEX
  - 831 SEXUALITY
  - 832 SEXUAL STIMULATION
  - 833 SEXUAL INTERCOURSE
  - 834 GENERAL SEX RESTRICTIONS
  - 835 KINSHIP REGULATION OF SEX
  - 836 PREMARITAL SEX RELATIONS
  - 837 EXTRAMARITAL SEX RELATIONS
  - 838 HOMOSEXUALITY
  - 839 MISCELLANEOUS SEX BEHAVIOR
  - 840 REPRODUCTION
  - 841 MENSTRUATION
  - 842 CONCEPTION
  - 843 PREGNANCY
  - 844 CHILDBIRTH
  - 845 DIFFICULT AND UNUSUAL BIRTHS
  - 846 POSTNATAL CARE
  - 847 ABORTION AND INFANTICIDE
  - 848 ILLEGITIMACY
  - 850 INFANCY AND CHILDHOOD
  - 851 SOCIAL PLACEMENT
  - 852 CEREMONIAL DURING INFANCY AND CHILDHOOD
  - 853 INFANT FEEDING
  - 854 INFANT CARE
  - 855 CHILD CARE
  - 856 DEVELOPMENT AND MATURATION
  - 857 CHILDHOOD ACTIVITIES
  - 858 STATUS OF CHILDREN
  - 860 SOCIALIZATION
  - 861 TECHNIQUES OF SOCIALIZATION
  - 862 WEANING AND FOOD TRAINING
  - 863 CLEANLINESS TRAINING
  - 864 SEX TRAINING
  - 865 AGGRESSION TRAINING
  - 866 INDEPENDENCE TRAINING
  - 867 TRANSMISSION OF CULTURAL NORMS
  - 868 TRANSMISSION OF SKILLS
  - 869 TRANSMISSION OF BELIEFS
  - 870 EDUCATION
  - 871 EDUCATION SYSTEM
  - 872 ELEMENTARY EDUCATION
  - 873 LIBERAL ARTS EDUCATION
  - 874 VOCATIONAL EDUCATION
  - 875 TEACHERS
  - 876 EDUCATIONAL THEORY AND METHODS
  - 877 STUDENTS
  - 880 ADOLESCENCE, ADULTHOOD, AND OLD AGE
  - 881 PUBERTY AND INITIATION
  - 882 STATUS OF ADOLESCENTS
  - 883 ADOLESCENT ACTIVITIES
  - 884 MAJORITY
  - 885 ADULTHOOD
  - 886 SENESCENCE
  - 887 ACTIVITIES OF THE AGED
  - 888 STATUS AND TREATMENT OF THE AGED
  - 890 GENDER ROLES AND ISSUES
  - 900 TEXTS
  - 901 TEXTS IN THE SPEAKER’S LANGUAGE
  - 902 TEXTS TRANSLATED INTO ENGLISH
  - 903 INTERLINEAR TRANSLATIONS
  - 910 ARCHAEOLOGICAL ANALYSES
  - 911 CHRONOLOGIES AND CULTURE SEQUENCES
  - 912 CULTURAL STRATIGRAPHY
  - 913 FUNCTIONAL SPECIALIZATION AREAS
  - 914 TYPOLOGIES AND CLASSIFICATIONS
  - 915 ARCHAEOLOGICAL INVENTORIES
