name: Build Spot containers
inputs:
  username:
    required: true
    description: "Username value for container repository"
  password:
    required: true
    description: "Password/token value for container repository"
  tag:
    required: true
    description: "Version identifier for release"
  application_image_name:
    required: false
    description: "Name to use for application container"
    default: "lafayette/rails"
  environment:
    required: false
    description: GitHub environment to use for variables
  fcrepo_image_name:
    required: false
    description: "Name to use for FCRepo container"
    default: "lafayette/fc"
  handle_image_name:
    required: false
    description: "Name to use for Handle server container"
    default: "lafayette/handle"
  registry:
    required: false
    description: "URL for container repository (default: DockerHub)"
    default: "docker.io"
  solr_image_name:
    required: false
    description: "Name to use for Solr container"
    default: "lafayette/solr"
  worker_image_name:
    required: false
    description: "Name to use for worker container"
    default: "lafayette/sidekiq"
runs:
  using: composite
  steps:
    -
      name: Log into Docker
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    -
      name: Set current build date
      run: |
        echo "build_date=$(date +'%Y%m%d')" >> $GITHUB_ENV
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push FCRepo container
      uses: ./.github/actions/build-container
      with:
        image_name: ${{ inputs.fcrepo_image_name }}
        context: ./docker/fcrepo
        registry: ${{ inputs.registry }}
        tag: ${{ inputs.tag }}
    -
      name: Build and push Solr container
      uses: ./.github/actions/build-container
      with:
        image_name: ${{ inputs.solr_image_name }}
        context: ./docker/solr
        registry: ${{ inputs.registry }}
        tag: ${{ inputs.tag }}
    -
      name: Build and push application container
      uses: ./.github/actions/build-container
      with:
        image_name: ${{ inputs.application_image_name }}
        build_args_json: "[\"build_date=$build_date\"]"
        context: .
        registry: ${{ inputs.registry }}
        tag: ${{ inputs.tag }}
        target: spot-web-production
    -
      name: Build and push worker container
      uses: ./.github/actions/build-container
      with:
        image_name: ${{ inputs.worker_image_name }}
        context: .
        registry: ${{ inputs.registry }}
        tag: ${{ inputs.tag }}
        target: spot-worker-production
