---
file_system:
  home: /spot/tmp/import
s3:
  bucket: <%= ENV['AWS_BULKRAX_IMPORTS_BUCKET'] %>
  app_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  app_secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-east-1
