development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] || "http://127.0.0.1:#{ENV.fetch('FCREPO_DEVELOPMENT_PORT', 8984)}/rest" %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_TEST_URL'] || "http://127.0.0.1:#{ENV.fetch('FCREPO_TEST_PORT', 8984)}/rest" %>
  base_path: /test
production:
  user: <%= ENV.fetch('FEDORA_USER') { 'fedoraAdmin' } %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL'] %>
  base_path: /ldr
