# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c753fc29e053f5770fe063a9f773ad7642ca0b8207ae392d792254841d10608766593240ef5d82a919c2d0a060d0bb28b82331a8f6be4c4f85ad05e0b37c5e28

test:
  secret_key_base: 4ba2cd4dff0873fbc48e136418407c479714b3ff4dbacdb412ee7e285f18be33cb4cbf69219786fa12d70cf949f14899a94e14b0e4b808224548c7f696615fb7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
