# Config file for Sidekiq
#
# See the capistrano-sidekiq section of `config/deploy.rb`
# for more detailed configuration (eg concurrency, # of processes).
# This lets us vary the settings per environment.
---
:verbose: false
:timeout: 30
:concurrency: 10
:logfile: <%= Rails.root.join('log', 'sidekiq.log') %>
:queues:
  - default
  - ingest
  - low_priority
