# Config file for Sidekiq
#
# See the capistrano-sidekiq section of `config/deploy.rb`
# for more detailed configuration (eg concurrency, # of processes).
# This lets us vary the settings per environment.
---
:verbose: false
:timeout: 30
:concurrency: 5
:queues:
  - default
  - ingest
  - mailers
  - import
  - export
  - low_priority
