# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_PORT', 8983)}/solr/spot-development" %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8983)}/solr/spot-test" %>
production:
  url: <%= ENV['SOLR_URL'] %>
