development:
  host: <%= ENV['VALKYRIE_SOLR_HOST'] %>
  port: <%= ENV['VALKYRIE_SOLR_PORT'] %>
  core: <%= ENV['VALKYRIE_SOLR_CORE'] || 'spot-development' %>
test:
  host: <%= ENV['VALKYRIE_SOLR_HOST'] %>
  port: <%= ENV['VALKYRIE_SOLR_PORT'] || 8983 %>
  core: <%= ENV['VALKYRIE_SOLR_CORE'] || 'spot-test' %>
production:
  host: <%= ENV['VALKYRIE_SOLR_HOST'] %>
  port: <%= ENV['VALKYRIE_SOLR_PORT'] %>
  core: <%= ENV['VALKYRIE_SOLR_CORE'] || 'spot' %>
