name: Build development containers
on:
  push:
    branches:
      - develop

  release:
    types:
      - prereleased

permissions:
  checks: write

jobs:
  lint_and_test:
    name: Lint + Test
    uses: ./.github/workflows/lint-and-test.yml

  build_and_push_development_containers:
    name: Build and push dev containers
    uses: ./.github/workflows/build-containers.yml
    needs: [lint_and_test]
    secrets:
      registry: ${{ secrets.CONTAINER_REGISTRY }}
      username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
    with:
      tag: ${{ github.event.release.tag_name || github.ref_name }}
      environments: '["stage"]'
      services: '["rails","sidekiq","fcrepo","solr","fits_servlet"]'

