name: Build release containers
on:
  release:
    types:
      - released

jobs:
  publish_release_containers:
    strategy:
      matrix:
        environment: [stage, production]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
      -
        name: Check out repo
        uses: actions/checkout@v3
      -
        name: Build and publish release containers in stage environment
        uses: ./.github/actions/build-containers
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          application_image_name: ${{ vars.APPLICATION_CONTAINER_ID }}
          worker_image_name: ${{ vars.WORKER_CONTAINER_ID }}
          fcrepo_image_name: ${{ vars.FCREPO_CONTAINER_ID }}
          handle_image_name: ${{ vars.HANDLE_CONTAINER_ID }}
          solr_image_name: ${{ vars.SOLR_CONTAINER_ID }}
