name: Build release containers
on:
  release:
    types:
      - released

jobs:
  publish_release_containers_stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      -
        name: Check out repo
        uses: actions/checkout@v3
      -
        name: Build and publish release containers in stage environment
        uses: ./.github/actions/build-containers
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          version_id: ${{ github.event.release.name }}
          application_container_id: ${{ vars.APPLICATION_CONTAINER_ID }}
          worker_container_id: ${{ vars.WORKER_CONTAINER_ID }}
          fcrepo_container_id: ${{ vars.FCREPO_CONTAINER_ID }}
          handle_container_id: ${{ vars.HANDLE_CONTAINER_ID }}
          solr_container_id: ${{ vars.SOLR_CONTAINER_ID }}
  publish_release_containers_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
     -
        name: Check out repo
        uses: actions/checkout@v3
      -
        name: Build and publish release containers in production environment
        uses: ./.github/actions/build-containers
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          version_id: ${{ github.event.release.name }}
          application_container_id: ${{ vars.APPLICATION_CONTAINER_ID }}
          worker_container_id: ${{ vars.WORKER_CONTAINER_ID }}
          fcrepo_container_id: ${{ vars.FCREPO_CONTAINER_ID }}
          handle_container_id: ${{ vars.HANDLE_CONTAINER_ID }}
          solr_container_id: ${{ vars.SOLR_CONTAINER_ID }}

