name: Build release containers
on:
  release:
    types:
      - released

permissions:
  checks: write

jobs:
  lint_and_test:
    name: Lint + Test
    uses: ./.github/workflows/lint-and-test.yml

  publish_release_containers:
    name: Build and push release containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_env: ["stage", "production"]
    environment: ${{ matrix.container_env }}
    needs: [lint_and_test]
    steps:
      -
        name: Check out repo
        uses: actions/checkout@v3
      -
        name: Build and publish release containers in ${{ matrix.container_env }} environment
        uses: ./.github/workflows/build-containers.yml
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          environments: '["${{ matrix.container_env }}"]'
          services: '["rails","sidekiq","fcrepo","solr","fits_servlet"]'
