name: Build containers
on:
  workflow_call:
    secrets:
      aws_role_to_assume:
        required: true
        description: "ARN of role to add containers to LDR's ECR"
    inputs:
      tag:
        type: string
        required: true
        description: "Version identifier for release"
      services:
        type: string
        required: true
        description: "Stringified JSON array of which service containers to build"
        default: '["rails","sidekiq","fcrepo","solr","fits_servlet"]'
      environments:
        type: string
        required: true
        description: Stringified JSON array of GitHub environments to use for variables
        default: '["stage","production"]'

permissions:
  id-token: write
  contents: read

jobs:
  build_containers:
    name: Build containers
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
        service: ${{ fromJson(inputs.services) }}
    steps:
      - uses: actions/checkout@v4
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: ${{ vars.AWS_REGION }}
      -
        name: Log into ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Get service config
        id: service
        env:
          CURRENT_SERVICE: ${{ matrix.service }}
        run: |
          config='{}'
          case "${CURRENT_SERVICE}" in
            "rails")
              echo "image=lafayette/rails" >> "$GITHUB_OUTPUT"
              echo "context=." >> "$GITHUB_OUTPUT"
              echo "target=spot-web-production" >> "$GITHUB_OUTPUT"
              ;;
            "sidekiq")
              echo "image=lafayette/sidekiq" >> "$GITHUB_OUTPUT"
              echo "context=." >> "$GITHUB_OUTPUT"
              echo "target=spot-worker-production" >> "$GITHUB_OUTPUT"
              ;;
            "solr")
              echo "image=lafayette/solr" >> "$GITHUB_OUTPUT"
              echo "context=./docker/solr" >> "$GITHUB_OUTPUT"
              ;;
            "fcrepo")
              echo "image=lafayette/fc" >> "$GITHUB_OUTPUT"
              echo "context=./docker/fcrepo" >> "$GITHUB_OUTPUT"
              ;;
            "fits_servlet")
              echo "image=lafayette/fits_servlet" >> "$GITHUB_OUTPUT"
              echo "context=./docker/fits_servlet" >> "$GITHUB_OUTPUT"
              ;;
          esac
      -
        name: Build and push ${{ steps.service.outputs.image }} container
        uses: ./.github/actions/build-container
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          tag: ${{ inputs.tag }}
          image_name: ${{ steps.service.outputs.image }}
          context: ${{ steps.service.outputs.context }}
          target: ${{ steps.service.outputs.target }}
