name: Build prerelease containers
on:
  push:
    branches:
      - develop

  release:
    types:
      - prereleased

jobs:
  lint_and_test:
    uses: ./.github/workflows/lint-and-test.yml

  publish_prerelease_containers:
    runs-on: ubuntu-latest
    environment: stage
    needs: [lint_and_test]
    steps:
      -
        name: Check out repo
        uses: actions/checkout@v3
      -
        name: Build and publish prerelease containers in stage environment
        uses: ./.github/actions/build-containers
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          application_image_name: ${{ vars.APPLICATION_CONTAINER_ID }}
          worker_image_name: ${{ vars.WORKER_CONTAINER_ID }}
          fcrepo_image_name: ${{ vars.FCREPO_CONTAINER_ID }}
          solr_image_name: ${{ vars.SOLR_CONTAINER_ID }}

