name: Lint and Test (on push)
on:
  push:
    branches-ignore:
      - develop

permissions:
  checks: write

jobs:
  lint_and_test:
    name: Lint + Test
    uses: ./.github/workflows/lint-and-test.yml