name: Lint + Test
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_WITH: test
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Run Rubocop
        run: bundle exec rubocop --format github

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.8-slim-bullseye
      volumes:
        - /tmp/solr:/tmp/solr
    needs: lint
    services:
      database:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: spot_test
          POSTGRES_USER: spot_test_user
          POSTGRES_PASSWORD: spot_test_pw
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      fedora:
        image: samvera/fcrepo4:4.7.5
        ports:
          - 8080:8080
        env:
          CATALINA_OPTS: '-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC'
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379
      solr:
        image: solr:8.11.4
        ports:
          - 8983:8983
        volumes:
          - /tmp/solr:/var/solr/data
        options: --name solrservice
    env:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_WITH: test
      CAS_BASE_URL: ''
      CI: 1
      FEDORA_TEST_URL: http://fedora:8080/rest
      IIIF_BASE_URL: http://localhost/iiif/2
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      PSQL_PASSWORD: spot_test_pw
      PSQL_USER: spot_test_user
      PSQL_DATABASE: spot_test
      PSQL_HOST: database
      RAILS_ENV: test
      SOLR_TEST_URL: http://localhost:8983/solr/spot-test
      SOLR_VERSION: "8.11.4"
      URL_HOST: http://localhost:3000

    steps:
      - uses: actions/checkout@v4
      - name: Copy Solr config to mount
        run: |
          mkdir -p /tmp/solr/spot-test/data
          cp -r docker/solr/config/* /tmp/solr/spot-test
          touch /tmp/solr/spot-test/core.properties
          chown -R 8983:8983 /tmp/solr/spot-test
      - name: Get Docker service status
        uses: docker://docker
        with:
          args: docker stats -a --no-stream
      - name: Stop Solr service
        uses: docker://docker
        with:
          args: docker stop solrservice
      - name: Start Solr service
        uses: docker://docker
        with:
          args: docker start solrservice
      -
        name: Install system dependencies from Dockerfile
        run: |
          apt-get update -y && apt-get install -y --no-install-recommends ca-certificates curl gnupg && \
          mkdir -p /etc/apt/keyrings && \
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
          echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
          apt-get update -y && apt-get install -y \
            build-essential coreutils curl git libxml2 libxml2-dev libxslt-dev \
            netcat-openbsd nodejs openssl postgresql-13 ruby-dev tzdata zip \
            libasound2 libdbus-glib-1-dev libgtk-3-0 libpq-dev unzip libx11-xcb1
      -
        name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        id: setup-firefox
        env:
          HOME: /root
        with:
          firefox-version: latest-esr
      -
        name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@latest
        id: setup-geckodriver
        env:
          HOME: /root
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          geckodriver-version: latest
      -
        name: Restore installed Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: spot-bundle-${{ hashFiles('Gemfile.lock') }}
      -
        name: Install gem dependencies
        run: |
          gem install bundler:$(tail -n 1 Gemfile.lock | sed -e "s/ *//")
          bundle install
      -
        name: Docker Stats
        uses: docker://docker
        with:
          args: docker stats --no-stream
      -
        name: Status check Solr
        run: |
          ls -al /tmp/solr/spot-test
          curl -I -fs -vvv $SOLR_TEST_URL || exit 1
      -
        name: Run migrations
        run: bundle exec rake db:migrate
      -
        name: Run tests
        env:
          FIREFOX_BINARY_PATH: ${{ steps.setup-firefox.outputs.firefox-path }}
          HOME: /root
        run: |
          export PATH="$(dirname $(which geckodriver)):${PATH}"
          mkdir /tmp/test-results
          bundle exec rspec --backtrace --format progress --format RspecJunitFormatter --out /tmp/test-results/rspec.xml
      -
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        continue-on-error: true
      -
        name: Publish RSpec report
        uses: mikepenz/action-junit-report@v3
        if: always()
        continue-on-error: true
        with:
          check_name: Test summary
          report_paths: /tmp/test-results/*.xml
      -
        name: Publish coverage
        uses: joshmfrankel/simplecov-check-action@main
        if: always()
        continue-on-error: true
        with:
          check_job_name: Test coverage
          minimum_suite_coverage: 95
          github_token: ${{ secrets.GITHUB_TOKEN }}